### PR TITLE
MAPI-1443: Update dependencies

### PR DESCRIPTION
**Pull request by agulowaty**
Upgraded several dependencies.
Removed management stuff for healthcheck and metric-related stuff (I suppose they were not used, correct me if I was wrong). If we really need these metrics I will create ticket for that.

cc @alexduf @pvighi @davidfurey

### CODE REVIEW

**Comment by alexduf** [comment]
It looks good but is the healthcheck endpoint still available?
if not you'll need to create one, even if it's just to return OK 200, and modify the cloudformation template so that the healthcheck is in the correct place (the new convention is /healthcheck rather than management/healthcheck)

**Comment by davidfurey** [comment]
Also the new convention is to run the healthcheck endpoint on the same port as the application

**Comment by agulowaty** [comment]
This route https://github.com/guardian/mobile-notifications-football/blob/master/src/main/scala/com/gu/mobile/notifications/football/GoalNotificationsService.scala#L88 acts as health check now

**Comment by alexduf** [comment]
But here we still have the healthcheck on the old endpoint: https://github.com/guardian/mobile-platform/blob/master/cloudformation/mobile-notifications/mobile-notifications-football.json#L128
It also has the security group open on the old management port

**Comment by agulowaty** [comment]
@alexduf: I created https://github.com/guardian/mobile-platform/pull/427 and added provisional /healthcheck endpoint. I'll create ticket for making it more tangible i.e. trying to contact PA API.

**Comment by alexduf** [comment]
:+1:

**Pull request merged**
